config/routes.rb
Rails.application.routes.draw do

  root 'rocks#index'

  namespace :api do
    namespace :v1 do
      namespace :rocks do
        get '/:id/web_detection', to: 'web_detection#show'
        get '/:id/label_detection', to: 'label_detection#show'
      end
      resources :rocks, only: [:index, :show, :create, :update, :destroy]
      end
    end

  resources :rocks, only: [:index, :new, :create, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rock.rb
require "google/cloud/vision"
require 'googleauth'

GOOGLE_APPLICATION_CREDENTIALS='gneiss-rocks-creds.json'

class Rock < ApplicationRecord
  has_attached_file :image,
                    styles: {
                    thumb: "100x100#",
                    small: "150x150>",
                    medium: "500x500" }

  validates_presence_of :location_found
  validates_presence_of :description
  validates_presence_of :image

  validates_attachment :image,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }



  def upload_file(image_path, rock)
    project_id = "gneiss-rocks"
    bucket_name = "gneiss-rocks"
    local_file_path   = image_path
    storage_file_path = nil

    require "google/cloud/storage"

    storage = Google::Cloud::Storage.new project: project_id
    bucket  = storage.bucket bucket_name

    file = bucket.create_file local_file_path, storage_file_path

    file.acl.public!

    puts "#{file.name} is publicly accessible at #{file.public_url}"
    rock.update(public_url: file.public_url)
  end

  def detect_labels(image_path)
    project_id = "gneiss-rocks"

    vision = Google::Cloud::Vision.new project: project_id

    labels = vision.image(image_path).labels

    puts "Labels:"
      labels.each do |label|
      puts label.description
    end
  end

  def web_detection(image_path)
    project_id = "gneiss-rocks"

    vision = Google::Cloud::Vision.new project: project_id
    image  = vision.image image_path

    web = image.web

    web.entities.each do |entity|
      puts entity.description
    end
  end
end

app/controllers/api/v1/rocks/label_detection_controller.rb
class Api::V1::Rocks::LabelDetectionController < ApplicationController
  def show
    render json: Rock.find(params[:id]).detect_labels(Rock.find(params[:id]).image.path)
  end
end

app/controllers/api/v1/rocks/web_detection_controller.rb
class Api::V1::Rocks::WebDetectionController < ApplicationController

  def show
    render json: Rock.find(params[:id]).web_detection(Rock.find(params[:id]).image.path)
  end
end

app/controllers/api/v1/rocks_controller.rb
class Api::V1::RocksController < ApplicationController

  def index
    render json: Rock.all
  end

  def show
    rock = Rock.find_by(id: params[:id])
    if rock
      render json: rock
    else
      render json: {"Error": "Item not found"}, status: 404
    end
  end

  def create
    rock = Rock.new(rock_params)

    if rock.save
      render json: rock
    else
      render json: rock.errors, status: 400
    end
  end

  def update
    rock = Rock.find(params[:id])

    if rock.update(rock_params)
      render json: rock
    else
      render json: rock.errors, status: 400
    end
  end

  def destroy
    rock = Rock.find(params[:id])
    if rock
      rock.destroy
      render json: {}, status: :no_content
    else
      render json: { "Error": "Can't find specified rock to delete" }, status: 404
    end
  end

  private

  def rock_params
    params.require(:rock).permit(:location_found, :description, :image, :image_file_name, :image_file_size, :image_content_type, :image_updated_at)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/rocks_controller.rb
class RocksController < ApplicationController

  def index
    @rocks = Rock.order('created_at')
  end

  def new
    @rock = Rock.new
  end

  def create
    @rock = Rock.new(rock_params)

    if @rock.save
      @rock.upload_file(@rock.image.path, @rock)
      flash[:success] = "Rock has been successfully created!"
      redirect_to root_path
    else
      flash[:error] = "Missing required fields"
      redirect_to new_rock_path
    end
  end

  def show
    @rock = Rock.find(params[:id])
    image_path = @rock.public_url
    @web_info = @rock.web_detection(image_path)
    @label_info = @rock.detect_labels(image_path)
  end

  def destroy
    @rock = Rock.find(params[:id])
    @rock.destroy
    flash[:notice] = "Rock was successfully destroyed."
    redirect_to root_path
  end

  private

  def rock_params
    params.require(:rock).permit(:location_found, :description, :image, :image_file_name, :image_file_size, :image_content_type, :image_updated_at, :public_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="google-site-verification" content="dzSvXM4RB-EMyYKUmlEQBDxl08SEnoB31c-hiiaWzEM">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GneissRocks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="main-nav">
      <ul class="nav-order">
        <li class="nav-link"><a href="/">GNEISS ROCKS</a></li>
        <li class="nav-link"><a href="/rocks/new">New Rock</a></li>
      </ul>
    </nav>


    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/rocks/_rock.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to image_tag(rock.public_url, class: 'media-object'), rock.public_url, target: '_blank' %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= rock.location_found %></h4>
    <p class="media-heading"><%= rock.description %></p>
    <%= button_to "Delete", rock, method: :delete, data: { confirm: "Are you sure?" }%>
    <%= link_to("See More", rock_path(rock.id), class: "btn") %>
  </div>
</div>

app/views/rocks/index.html.erb
<h1>Gneiss Rocks</h1>

<p>Keep in mind that this information is just a guess, it is determined by the quality of photograph and by the google vision API. Use what you find here as supplementary to your educational guesses as to the identification of rocks. </p>

<%= render @rocks %>

app/views/rocks/new.html.erb
<h1>Upload a Rock</h1>

<%= form_for @rock do |f| %>
  <%= render 'shared/errors', object: @rock %>

  <div class="form-group">
    <%= f.label :location_found %>
    <%= f.text_field :location_found, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
  </div>

  <%= f.submit 'Create Rock', class: 'btn btn-primary' %>
<% end %>

app/views/rocks/show.html.erb
<h1>Potentially Accurate Information About This Rock</h1>

<%= @rock.location_found %>
<%= @rock.description %>

<div class="media-left">
    <%= link_to image_tag(@rock.public_url, class: 'media-show'), @rock.public_url, target: '_blank' %>
</div>

<h2>Web Detection</h2>

<div id="web_detection">
  <% @web_info.each do |info| %>
    <ul>
      <li> Score: <%= info.score %> </li>
      <li> Description: <%= info.description %> </li>
    </ul>
  <% end %>
</div>

<h2>Label Detection</h2>

<div id="rock-labels">
  <% @label_info.each do |label| %>
    <ul>
      <li> Score: <%= label.score %> </li>
      <li> Description: <%= label.description %> </li>
    </ul>
  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>